#' Download Sentinel-2 data from a list
#'
#' \code{sent_down} is a function to download Sentinel-2 data from a list
#' generated from a search of the Australian Regional Copernicus Hub. The list
#' is generated by using the auscophub_searchServer.py python script. See
#' \href{http://auscophub.readthedocs.io/en/latest/}{here} or the package
#' vignette for details.
#'
#' @param wdir A character string representing the file path to your working
#' directory which will be the location of the text file of data to download.
#' File path should be of the type Z:/DOCUMENTATION/..." or double up the
#' backslashes if on Windows.
#'
#' @param ddir A character string representing the file path to your download
#' directory which will be where you want the data to download to. File path
#' should be of the type Z:/DOCUMENTATION/..." or double up the backslashes if
#' on Windows. The default is "Y:/sentinel/zdownloads".
#'
#' @param file A character string of the name of the text file that contains the
#' addresses of Sentinel data to download. It must include the file extension.
#' The default is "aoi_download_list.txt"
#'
#' @return This function downloads zipped files of Sentinel-2 data from the
#' Australian Regional Copernicus Hub to a destination of your choice.
#'
#' @examples
#' \dontrun{
#' sent_down(wdir = "Z:/blah/working", ddir = "Z:/blah/downloads", file = "test.txt")}
#'
#' @export
sent_down <- function(wdir, ddir = "Y:/sentinel/zdownloads" ,
                      file = "aoi_download_list.txt"){
  setwd(wdir)
  dlist <- read.table(file, stringsAsFactors = FALSE)
  setwd(ddir)
  for(i in 1:length(dlist[,1])){
    url <- dlist[i,1]
    urlname <- paste0(".//", strsplit(url, "/")[[1]][14])
    download.file(url, destfile = urlname)
  }
}

#' Create archive folder directory for Sentinel-2 data downloads
#'
#'  \code{sent_dirs} is a function that will create a directory tree which will
#'  be the final resting place for extracted files from the downloaded zip file.
#'  Specifically it will create for each downloaded zip file a tile directory
#'  (if it doesn't already exist) and within that a folder named for the date of
#'  image capture. It is written to work from the location of the zip files.
#'
#'
#' @return This function will create a directory for the tile and the date of
#'  imagery (all extracted from the zip file name) if they do not already exist.
#'
#' @examples
#' \dontrun{
#' sent_dirs()}
sent_dirs <- function(){
  zlist <- list.files(pattern = ".zip")
  for(i in 1:length(zlist)){
    tiledir <- strsplit(zlist[i], "_")[[1]][6]
    sentdate <- substr(strsplit(zlist[i], "_")[[1]][3], 1, 8)
    setwd("..")
    if(!file.exists(tiledir)){
      dir.create(tiledir)
    }
    setwd(paste0("./", tiledir))
    if(!file.exists(sentdate)){
      dir.create(sentdate)
    }
  }
}

#' Extract jp2 band data from Sentinel-2 downloaded zip files into local archive
#'
#' \code{sent_sort} will unzip downloaded Sentinel-2 data to a temp file,
#' extract just the jp2 formatted bands, create a local archive
#' (sentinel/TILE/YYYYMMDD) and move the products and original zip file to the
#' new archive.
#'
#' @note This function will:
#' \itemize{
#'   \item Create a directory tree which includes a folder for the tile name (if
#'   it doesn't exist) and within that, a folder for the data overpass date.
#'   \item Extract all jp2 band data to a temporary file and then copy to the
#'   appropriate archive folder.
#'   \item Move the original zip file to the appropriate archive folder}
#'
#' @param topdir A character string representing the top level in the local
#' archive. The default is the RS Section's sentinel archive "Y:/sentinel".
#'
#' @param ddir A character string representing the download folder in the local
#' archive. The default is the RS Section's sentinel archive
#' "Y:/sentinel/zdownloads.
#'
#' @return This function will manage the downloaded Sentinel-2 data zip files
#' into a folder structure similar to the RS section USGS Landsat archive.
#'
#' @importFrom utils download.file read.table unzip
#'
#' @examples
#' \dontrun{
#' sent_sort()}
#'
#' @export
sent_sort <- function(topdir = "Y:/sentinel", ddir = "Y:/sentinel/zdownloads"){
  setwd(ddir)
  sent_dirs()
  setwd(ddir)
  zlist <- list.files(pattern = ".zip")
  for(i in 1:length(zlist)){
    tiledir <- strsplit(zlist[i], "_")[[1]][6]
    sentdate <- substr(strsplit(zlist[i], "_")[[1]][3], 1, 8)
    topath <- paste(topdir, tiledir, sentdate, sep = "/")
    temp <- tempdir()
    all <- unzip(zlist[i], junkpaths = TRUE, exdir = temp)
    jps <- all[grepl(pattern = ".jp2", all)]
    #jp2 copies
    from <- jps
    to <- paste(topath, basename(jps), sep = "/")
    file.copy(from, to)
    #move zip
    fromr <- paste(ddir, zlist[i], sep = "/")
    tor <- paste(topath, zlist[i], sep = "/")
    file.rename(fromr, tor)
    unlink(temp, recursive=TRUE)
    cat("sorted: ", zlist[i], "\n")
  }

}
