#' Download Sentinel-2 data from a list
#'
#' \code{sent_down} is a function to download Sentinel-2 data from a list
#' generated from a search of the Australian Regional Copernicus Hub. The list
#' is generated by using the auscophub_searchServer.py python script. See
#' \href{http://auscophub.readthedocs.io/en/latest/}{here} or the package
#' vignette for details.
#'
#' @param wdir A character string representing the file path to your working
#' directory which will be the location of the text file of data to download.
#' File path should be of the type Z:/DOCUMENTATION/..." or double up the
#' backslashes if on Windows
#'
#' @param ddir A character string representing the file path to your download
#' directory which will be where you want the data to download to. File path
#' should be of the type Z:/DOCUMENTATION/..." or double up the backslashes if
#' on Windows.
#'
#' @param aoi A character string of the name of the text file that contains the
#' addresses of Sentinel data to download. It must include the file extension.
#' The default is "aoi_list.txt"
#'
#' @return This function downloads zipped files of Sentinel-2 data from the
#' Australian Regional Copernicus Hub to a destination of your choice.
#'
#' @examples
#' \dontrun{
#' sent_down(wdir = "Z:/blah/working", ddir "Z:/blah/downloads", aoi = "test.txt")}
#'
#' @export
sent_down <- function(wdir, ddir, aoi = "aoi_list.txt"){
  setwd(wdir)
  dlist <- read.table(aoi, stringsAsFactors = FALSE)
  setwd(ddir)
  for(i in 1:length(dlist[,1])){
    url <- dlist[i,1]
    urlname <- paste0(".//", strsplit(url, "/")[[1]][14])
    download.file(url, destfile = urlname)
  }
}
